name: package

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libarchive-tools dpkg-dev
          
      - name: Build armhf
        run: |
          rm -rf ./broot*/
          export version=$(curl -s https://api.github.com/repos/Canop/broot/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          mkdir broot-base
          mkdir -p broot-base/DEBIAN
          mkdir -p broot-base/usr/bin
          wget https://dystroy.org/broot/download/armv7-unknown-linux-gnueabihf/broot -O broot-base/usr/bin/broot
          echo "Package: broot
Version: ${version}
Section: net
Priority: optional
Architecture: armhf
Depends: bash
Maintainer: Ryan Fortner <ryankfortner@gmail.com>
Description: A new way to see and navigate directory trees
Homepage: https://dystroy.org/broot/
Bugs: https://github.com/Canop/broot/issues" > broot-base/DEBIAN/control
          dpkg-deb -b ./broot-base broot_"$version"_armhf.deb

      - name: Upload
        run: |
          rm -rf ./broot*/
          export version=$(curl -s https://api.github.com/repos/Canop/broot/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')
          export current=$(cat current.txt)
          [ "$current" == "$version" ] && exit 0
          echo $version > current.txt
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload blockbench v$(curl -s https://api.github.com/repos/Canop/broot/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')" 
          git push
